<?php

namespace PlentyOne\Api\Dto;

use Spatie\LaravelData\Data as SpatieData;

class User extends SpatieData
{
	public function __construct(
		public ?int $id = null,
		public ?string $user = null,
		public ?string $realName = null,
		public ?string $lang = null,
		public ?string $ipLimit = null,
		public ?bool $ustatus = null,
		public ?int $memberId = null,
		public ?string $timestamp = null,
		public ?string $email = null,
		public ?string $timezone = null,
		public ?string $googleEmail = null,
		public ?string $skype = null,
		public ?string $ical = null,
		public ?bool $psConfig = null,
		public ?bool $psItem = null,
		public ?bool $psEbay = null,
		public ?bool $psStock = null,
		public ?bool $psCustomer = null,
		public ?bool $psOrder = null,
		public ?bool $psStats = null,
		public ?bool $psData = null,
		public ?bool $pcConfig = null,
		public ?bool $pcContent = null,
		public ?bool $pcNewsletter = null,
		public ?bool $pcLayout = null,
		public ?bool $pcDialog = null,
		public ?bool $pcStats = null,
		public ?bool $pcData = null,
		public ?bool $pcBlog = null,
		public ?string $signature = null,
		public ?string $color = null,
		public ?bool $eks = null,
		public ?bool $payments = null,
		public ?int $acceptAgb = null,
		public ?bool $api = null,
		public ?string $image = null,
		public ?bool $delOrder = null,
		public ?bool $delArticle = null,
		public ?bool $delRecord = null,
		public ?bool $plentystat = null,
		public ?bool $plentyconnect = null,
		public ?bool $webspaceAccess = null,
		public ?string $accessControlList = null,
		public ?bool $plentymarketsShippingOrderId = null,
		public ?bool $plentymarketsShippingItem = null,
		public ?bool $plentymarketsShippingAuto = null,
		public ?bool $plentymarketsShippingLabel = null,
		public ?bool $plentymarketsShippingConfig = null,
		public ?int $warehouseId = null,
		public ?bool $calendar = null,
		public ?string $orderStatus = null,
		public ?int $warehouseRepairId = null,
		public ?bool $project = null,
		public ?bool $ticket = null,
		public ?bool $order = null,
		public ?bool $blog = null,
		public ?bool $lead = null,
		public ?bool $customer = null,
		public int|float|null $totalVacationDays = null,
		public ?int $roleId = null,
		public ?string $salutation = null,
		public ?string $dataLang = null,
		public ?bool $disabled = null,
		public ?bool $scheduler = null,
		public ?bool $item = null,
		public ?bool $incomingItems = null,
		public ?int $backendPluginSetId = null,
	) {
	}
}
